name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.0.2
        with: 
          auto-update-conda: true
          python-version: 3.8

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          which python

      - name: Conda install FEniCS
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          conda create -n fenicsproject -c conda-forge fenics
          conda activate fenicsproject
          which python
          python -c "from dolfin import *"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install --upgrade jax jaxlib

      # - name: Install FEniCS
      #   run: |
      #     sudo apt-get install software-properties-common
      #     sudo add-apt-repository ppa:fenics-packages/fenics
      #     sudo apt-get update
      #     sudo apt-get install --no-install-recommends fenics
      #     which python3
      #     python3 -c "from dolfin import *"

      - name: Install JAX-FEniCS
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pip install .

      - name: Print path
        shell: bash -l {0}
        run: python -c "import sys; print('\n'.join(sys.path))"

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          # export PYTHONPATH="/usr/lib/python3/dist-packages:${PYTHONPATH}"
          conda activate fenicsproject
          python -c "import sys; print('\n'.join(sys.path))"
          python -m pytest tests/