name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install --upgrade jax jaxlib

      - name: Install FEniCS
        run: |
          sudo apt-get install software-properties-common
          sudo add-apt-repository ppa:fenics-packages/fenics
          sudo apt-get update
          sudo apt-get install --no-install-recommends fenics

      - name: Install JAX-FEniCS
        run: |
          python -m pip install .

      - name: Test with pytest
        run: pytest tests/